### ISSUE TITLE
assume gemini:// if no other URI scheme is provided

### ISSUE THREAD

**Issue by non** [audiodude/ismygem.online#1]
Since the site currently only checks Gemini sites it might be nice to let users leave "gemini://" off the start of the URL.

**Comment by audiodude** [comment]
Yes, I considered that. I think I was hesitant because I wanted users to type the `gemini://` to avoid confusion and be sure they are checking a Gemini site. I guess what I want to avoid is someone typing in `google.com` and then getting confused that the site checked `gemini://google.com`, but maybe that's not an issue?

**Comment by non** [comment]
I think if the response message includes the `gemini://` then people will hopefully not be too confused.

I experienced the reverse confusion (was surprised when checking a site that it wasn't found, before reading the error more carefully and realizing I needed to add `gemini://`).

Anyway thanks for creating this site!

**Comment by audiodude** [comment]
Playing around with the validation and error messaging just now, it seems that the builtin HTML validation for `type="url"` won't pass unless there is a scheme (`http://` or `gemini://`). So if I don't require `gemini://`, I can't easily validate that the input is a URL (only valid characters, doesn't have spaces, etc).

**Comment by audiodude** [comment]
> Anyway thanks for creating this site!

My pleasure, it was fun! I plan to set up "uptimerobot" type checking in the future, which is the main use case I have for it (hate when my certs don't renew and my gem capsule goes down).

**Comment by audiodude** [comment]
Maybe I can autofill the input with `gemini://` when it's empty and receives focus

**Comment by audiodude** [comment]
> Maybe I can autofill the input with `gemini://` when it's empty and receives focus

Actually scratch that idea, it would be terrible for accessibility.

**Comment by non** [comment]
Sounds like it would be more hassle than it's worth. Thanks for exploring the idea! Happy to close this one for now.

**Comment by audiodude** [comment]
It turns out that `type="url"` wasn't providing particularly great validation, it was mostly just checking for a scheme. Got rid of it and implemented your suggestion, thanks!
